import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
 const [results, setResults] = useState("");
 const [show, setShow] = useState("");

 const submitHandler = (e) => {
  e.preventDefault();
  console.log(results);
 };
 return (
  <>
   <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>
   <div className="text-center text-5xl mb-6">Прогнозист 2023</div>
   <form
    onSubmit={(e) => submitHandler(e)}
    className="flex items-center ml-[50%] translate-x-[-50%]"
   >
    <input
     value={show}
     onChange={(e) => setShow(e.target.value)}
     placeholder="Название шоу"
     className="border-4 border-slate-900 focus:outline-none rounded-2xl mx-5 p-2"
    ></input>
    <textarea
     cols="50"
     rows="10"
     placeholder="Данные..."
     value={results}
     onChange={(e) => setResults(e.target.value)}
     className="border-4 border-slate-900 focus:outline-none rounded-2xl mx-5 p-2"
    ></textarea>
    <button className="mx-5 bg-slate-900 p-3 border-2 border-slate-900 duration-300 text-slate-50 hover:bg-slate-50 hover:text-slate-900">
     Отправить
    </button>
   </form>
  </>
 );
}
